version: '3.7'

services:
  app:
    container_name: unyhosp_api
    build: .
    command: bash -c "python manage.py migrate
      && python manage.py collectstatic --no-input --clear
      && gunicorn unyhosp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/usr/src/unyhosp-api/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure:10
  db:
    container_name: unyhosp_database
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'unyhosp'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/unyhosp-api/staticfiles
      - media_volume:/usr/src/unyhosp-api/mediafiles
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  mysql_data:
  static_volume:
  media_volume: