version: '3.7'

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/unyhosp-api/
    ports:
      - 8000:8000
    env_file:
      - .env
