version: '3.7'

services:
  api:
    container_name: unyhosp
    build: .
    command: bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/unyhosp-api/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure:10
  db:
    container_name: unyhosp_database
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'unyhosp'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'