version: '3.7'

services:
  app:
    container_name: unyhosp_api
    build: .
    command: bash -c "python manage.py migrate
      && python manage.py collectstatic --no-input --clear
      && gunicorn unyhosp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/usr/src/unyhosp-api/staticfiles
    expose:
      - 8000
    env_file:
      - .env

volumes:
  static_volume: