# Generated by Django 3.0 on 2020-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='atb',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comorbidity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='complications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='cultures',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='diet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='entry_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hma',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='medicines_in_use',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='previous_pathologies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='probes_and_drains',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sedation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='therapeutic_plan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='vasoactive_drugs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='venous_access',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ventilation',
            field=models.TextField(null=True),
        ),
    ]
